/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.wittho;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;

@SpringBootApplication
public class EventosApplication {

  public static void main(String[] args) {
    SpringApplication.run(EventosApplication.class, args);
  }

}
